# Generated by Django 5.2.7 on 2025-10-29 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_car_description_car_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='image',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
