export const caps = {
    'admin': [
        'super_cap',
        'view_admin',
        'manage_admin',
        'view_doctor',
        'manage_doctor',
        'view_patient',
        'manage_patient',
        'view_email',
        'manage_email',
        'set_status_patient',
        'view_patient_log',
        'manage_patient_log',
        'view_appointment',
        'manage_appointment',
        'view_slot_type',
        'manage_slot_type',
        'manage_student',
        'view_student',
        'view_holiday',
        'manage_holiday',
        'view_service',
        'manage_service',
        'view_email_template',
        'manage_email_template',
        'view_testimonial',
        'manage_testimonial',
        'manage_settings',
        'manage_social_media',
        'view_social_media',
        'manage_banner',
        'view_banner',
        'manage_order',
        'view_order',
    ],
    'doctor': [
        'view_patient',
        'manage_patient',
        'set_status_patient',
        'view_patient_log',
        'manage_patient_log',
    ],
    'patient': []
}
